# Generated by Django 5.2.13 on 2026-04-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeFile',
            fields=[
                ('resume_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(db_index=True, max_length=500)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_files', to='users.appuser')),
            ],
            options={
                'db_table': 'resume_files',
                'indexes': [models.Index(fields=['user', 'deleted_at'], name='resume_user_deleted_idx')],
            },
        ),
    ]
