# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumefile",
            name="extracted_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
