# Generated by Django 5.2.13 on 2026-04-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('deleted', 'Deleted')], db_index=True, max_length=20)),
                ('mode', models.CharField(max_length=50)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('consumed_minutes', models.IntegerField(default=0)),
                ('remaining_credit_minutes_after', models.IntegerField(blank=True, null=True)),
                ('used_fallback', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='resumes.resumefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='users.appuser')),
            ],
            options={
                'db_table': 'interview_sessions',
            },
        ),
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('message_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_index=True, max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], max_length=20)),
                ('content', models.TextField()),
                ('ai_mode', models.CharField(blank=True, choices=[('azure', 'Azure'), ('fallback', 'Fallback')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interviews.interviewsession')),
            ],
            options={
                'db_table': 'interview_messages',
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('reflection_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('strengths', models.TextField()),
                ('improvements', models.TextField()),
                ('advice', models.TextField()),
                ('ai_mode', models.CharField(choices=[('azure', 'Azure'), ('fallback', 'Fallback')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='interviews.interviewsession')),
            ],
            options={
                'db_table': 'reflections',
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['user', '-started_at'], name='session_user_started_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewmessage',
            index=models.Index(fields=['session', 'created_at'], name='message_session_created_idx'),
        ),
    ]
