# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewmessage",
            name="ai_mode",
            field=models.CharField(
                blank=True,
                choices=[("openai", "OpenAI"), ("azure", "Azure"), ("fallback", "Fallback")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reflection",
            name="ai_mode",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("azure", "Azure"), ("fallback", "Fallback")],
                max_length=20,
            ),
        ),
    ]
