# Generated by Django 5.2.13 on 2026-04-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('auth_provider', models.CharField(choices=[('demo', 'Demo'), ('cognito', 'Cognito')], db_index=True, max_length=20)),
                ('external_subject', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], db_index=True, default='user', max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('target_job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('interview_goal', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.appuser')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
