# Generated by Django 5.2.13 on 2026-04-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('balance_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('available_minutes', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to='users.appuser')),
            ],
            options={
                'db_table': 'credit_balances',
            },
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('payment_session_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stripe_checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('reflected', 'Reflected')], db_index=True, max_length=20)),
                ('plan_code', models.CharField(max_length=50)),
                ('amount_jpy', models.IntegerField()),
                ('purchased_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='users.appuser')),
            ],
            options={
                'db_table': 'payment_sessions',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('grant', 'Grant'), ('consume', 'Consume'), ('adjust', 'Adjust'), ('purchase', 'Purchase')], db_index=True, max_length=20)),
                ('minutes_delta', models.IntegerField()),
                ('amount_jpy', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='users.appuser')),
                ('payment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='billing.paymentsession')),
            ],
            options={
                'db_table': 'credit_transactions',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_log_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_index=True, max_length=50)),
                ('target_type', models.CharField(db_index=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.appuser')),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['action_type', '-created_at'], name='audit_action_created_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['user', '-created_at'], name='payment_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['user', '-created_at'], name='credit_tx_user_created_idx'),
        ),
    ]
