# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsession",
            name="checkout_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="paymentsession",
            name="idempotency_key",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
